export const templateData = {
    "resource": {
      "error": {
        "no": 0,
        "text": "template_files"
      },
      "files": [
        {
          "_id": 1415,
          "user_id": 448,
          "length": 3,
          "orig_filename": "NIxvG26r3bqj83LI.wav",
          "map_filename": "NIxvG26r3bqj83LI.wav",
          "extension": "wav",
          "stripped_name": "NIxvG26r3bqj83LI",
          "tts_language": "Veena",
          "tts_text": "Esto es texto con ingles india",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 22:06:19",
          "updated_at": "2019-03-27 22:06:19"
        },
        {
          "_id": 1414,
          "user_id": 448,
          "length": 2,
          "orig_filename": "bGHYF65cTSBHjp7E.wav",
          "map_filename": "bGHYF65cTSBHjp7E.wav",
          "extension": "wav",
          "stripped_name": "bGHYF65cTSBHjp7E",
          "tts_language": "Monica",
          "tts_text": "Esto es texto",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 22:06:05",
          "updated_at": "2019-03-27 22:06:05"
        },
        {
          "_id": 1413,
          "user_id": 448,
          "length": 3,
          "orig_filename": "deaVlwFVuNwg6eqD.wav",
          "map_filename": "deaVlwFVuNwg6eqD.wav",
          "extension": "wav",
          "stripped_name": "deaVlwFVuNwg6eqD",
          "tts_language": "Veena",
          "tts_text": "Esto es español  con ingles india",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 22:05:26",
          "updated_at": "2019-03-27 22:05:26"
        },
        {
          "_id": 1412,
          "user_id": 448,
          "length": 3,
          "orig_filename": "s8PwDYHUDxhe6XVO.wav",
          "map_filename": "s8PwDYHUDxhe6XVO.wav",
          "extension": "wav",
          "stripped_name": "s8PwDYHUDxhe6XVO",
          "tts_language": "Veena",
          "tts_text": "Esto es español  con ingles india",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 22:05:17",
          "updated_at": "2019-03-27 22:05:17"
        },
        {
          "_id": 1411,
          "user_id": 448,
          "length": 3,
          "orig_filename": "vdRMAjsbE2Qj4BTh.wav",
          "map_filename": "vdRMAjsbE2Qj4BTh.wav",
          "extension": "wav",
          "stripped_name": "vdRMAjsbE2Qj4BTh",
          "tts_language": "Veena",
          "tts_text": "Esto es español  con ingles india",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 22:05:09",
          "updated_at": "2019-03-27 22:05:09"
        },
        {
          "_id": 1410,
          "user_id": 448,
          "length": 2,
          "orig_filename": "9MFDvJNPS3N82uAF.wav",
          "map_filename": "9MFDvJNPS3N82uAF.wav",
          "extension": "wav",
          "stripped_name": "9MFDvJNPS3N82uAF",
          "tts_language": "Monica",
          "tts_text": "Esto es español",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 22:04:56",
          "updated_at": "2019-03-27 22:04:56"
        },
        {
          "_id": 1409,
          "user_id": 448,
          "length": 2,
          "orig_filename": "NDBcjzfznpZIyQ1F.wav",
          "map_filename": "NDBcjzfznpZIyQ1F.wav",
          "extension": "wav",
          "stripped_name": "NDBcjzfznpZIyQ1F",
          "tts_language": "Monica",
          "tts_text": "Seccion de texto 1",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 21:56:11",
          "updated_at": "2019-03-27 21:56:11"
        },
        {
          "_id": 1408,
          "user_id": 448,
          "length": 2,
          "orig_filename": "w5Xqg04WN38lc9OM.wav",
          "map_filename": "w5Xqg04WN38lc9OM.wav",
          "extension": "wav",
          "stripped_name": "w5Xqg04WN38lc9OM",
          "tts_language": "Monica",
          "tts_text": "Seccion de texto",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 21:56:07",
          "updated_at": "2019-03-27 21:56:07"
        },
        {
          "_id": 1407,
          "user_id": 448,
          "length": 5,
          "orig_filename": "iwDQ8opryB25gAfQ.wav",
          "map_filename": "iwDQ8opryB25gAfQ.wav",
          "extension": "wav",
          "stripped_name": "iwDQ8opryB25gAfQ",
          "tts_language": "Monica",
          "tts_text": "Vamos a ver que hace esto si pruebo con un texto mucho mas largo de una linea por ejemplo",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 21:56:00",
          "updated_at": "2019-03-27 21:56:00"
        },
        {
          "_id": 1406,
          "user_id": 448,
          "length": 5,
          "orig_filename": "687bvxiigXdcbCM3.wav",
          "map_filename": "687bvxiigXdcbCM3.wav",
          "extension": "wav",
          "stripped_name": "687bvxiigXdcbCM3",
          "tts_language": "Monica",
          "tts_text": "Vamos a ver que hace esto si pruebo con un texto mucho mas largo de una linea por ejemplo",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 21:55:47",
          "updated_at": "2019-03-27 21:55:47"
        },
        {
          "_id": 1405,
          "user_id": 448,
          "length": 5,
          "orig_filename": "MqgO6dwEcwSqnxRQ.wav",
          "map_filename": "MqgO6dwEcwSqnxRQ.wav",
          "extension": "wav",
          "stripped_name": "MqgO6dwEcwSqnxRQ",
          "tts_language": "Monica",
          "tts_text": "Vmaos a ver que hace esto si pruebo con un texto mucho mas largo de una linea por ejemplo",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 21:55:37",
          "updated_at": "2019-03-27 21:55:37"
        },
        {
          "_id": 1404,
          "user_id": 448,
          "length": 2,
          "orig_filename": "imHq5gz4G4PAZCbi.wav",
          "map_filename": "imHq5gz4G4PAZCbi.wav",
          "extension": "wav",
          "stripped_name": "imHq5gz4G4PAZCbi",
          "tts_language": "Monica",
          "tts_text": "Esto es una prueba DNIMO",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-27 17:53:27",
          "updated_at": "2019-03-27 17:53:27"
        },
        {
          "_id": 1403,
          "user_id": 448,
          "length": 1,
          "orig_filename": "cFTYVEvDme80hJaJ.wav",
          "map_filename": "cFTYVEvDme80hJaJ.wav",
          "extension": "wav",
          "stripped_name": "cFTYVEvDme80hJaJ",
          "tts_language": "Kate",
          "tts_text": "hello",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-03-20 11:38:22",
          "updated_at": "2019-03-20 11:38:22"
        },
        {
          "_id": 1402,
          "user_id": 448,
          "length": 8,
          "orig_filename": "EBBvGXc3FdciHSrw.wav",
          "map_filename": "EBBvGXc3FdciHSrw.wav",
          "extension": "wav",
          "stripped_name": "EBBvGXc3FdciHSrw",
          "tts_language": "Kate",
          "tts_text": "+3-4-6-0-9-3-7-8-8-4-5‬",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2019-03-17 21:09:44",
          "updated_at": "2019-03-17 21:09:44"
        },
        {
          "_id": 1401,
          "user_id": 448,
          "length": 1,
          "orig_filename": "XC9aCGBTQJoklRu3.wav",
          "map_filename": "XC9aCGBTQJoklRu3.wav",
          "extension": "wav",
          "stripped_name": "XC9aCGBTQJoklRu3",
          "tts_language": "Kate",
          "tts_text": "awaw",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-02-04 09:33:08",
          "updated_at": "2019-02-04 09:33:08"
        },
        {
          "_id": 1399,
          "user_id": 448,
          "length": 1,
          "orig_filename": null,
          "map_filename": null,
          "extension": null,
          "stripped_name": null,
          "tts_language": null,
          "tts_text": "cqcqcq",
          "is_template": 1,
          "cost": 0,
          "type": "SMS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-02-04 09:24:57",
          "updated_at": "2019-02-04 09:24:57"
        },
        {
          "_id": 1398,
          "user_id": 448,
          "length": 2,
          "orig_filename": "6bNwZ6WJXLa7n104.wav",
          "map_filename": "6bNwZ6WJXLa7n104.wav",
          "extension": "wav",
          "stripped_name": "6bNwZ6WJXLa7n104",
          "tts_language": "Kate",
          "tts_text": "vwvwv",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "CALL_ME_BACK",
          "created_at": "2019-02-04 09:19:45",
          "updated_at": "2019-02-04 09:19:45"
        },
        {
          "_id": 1397,
          "user_id": 448,
          "length": 2,
          "orig_filename": "miJ3otofonGQh4gt.wav",
          "map_filename": "miJ3otofonGQh4gt.wav",
          "extension": "wav",
          "stripped_name": "miJ3otofonGQh4gt",
          "tts_language": "Kate",
          "tts_text": "fqfqf",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-02-04 09:19:33",
          "updated_at": "2019-02-04 09:19:33"
        },
        {
          "_id": 1396,
          "user_id": 448,
          "length": 2,
          "orig_filename": "4L0UaOtipFBCcrY6.wav",
          "map_filename": "4L0UaOtipFBCcrY6.wav",
          "extension": "wav",
          "stripped_name": "4L0UaOtipFBCcrY6",
          "tts_language": "Kate",
          "tts_text": "aaaa",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "CALL_ME_BACK",
          "created_at": "2019-01-22 12:22:37",
          "updated_at": "2019-01-22 12:22:37"
        },
        {
          "_id": 1395,
          "user_id": 448,
          "length": 1,
          "orig_filename": null,
          "map_filename": null,
          "extension": null,
          "stripped_name": null,
          "tts_language": null,
          "tts_text": "jij",
          "is_template": 1,
          "cost": 0,
          "type": "SMS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-01-22 12:19:22",
          "updated_at": "2019-01-22 12:19:22"
        },
        {
          "_id": 1394,
          "user_id": 448,
          "length": 2,
          "orig_filename": "6pRv0HwKijmsxpAc.wav",
          "map_filename": "6pRv0HwKijmsxpAc.wav",
          "extension": "wav",
          "stripped_name": "6pRv0HwKijmsxpAc",
          "tts_language": "Kate",
          "tts_text": "aaaaa",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-01-22 12:12:53",
          "updated_at": "2019-01-22 12:12:53"
        },
        {
          "_id": 1393,
          "user_id": 448,
          "length": 1,
          "orig_filename": null,
          "map_filename": null,
          "extension": null,
          "stripped_name": null,
          "tts_language": null,
          "tts_text": "titi",
          "is_template": 1,
          "cost": 0,
          "type": "SMS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-01-22 12:06:05",
          "updated_at": "2019-01-22 12:06:05"
        },
        {
          "_id": 1392,
          "user_id": 448,
          "length": 1,
          "orig_filename": null,
          "map_filename": null,
          "extension": null,
          "stripped_name": null,
          "tts_language": null,
          "tts_text": "uloyl",
          "is_template": 1,
          "cost": 0,
          "type": "SMS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-01-22 12:05:48",
          "updated_at": "2019-01-22 12:05:48"
        },
        {
          "_id": 1391,
          "user_id": 448,
          "length": 2,
          "orig_filename": "7kf3JqfkjspnGsr2.wav",
          "map_filename": "7kf3JqfkjspnGsr2.wav",
          "extension": "wav",
          "stripped_name": "7kf3JqfkjspnGsr2",
          "tts_language": "Kate",
          "tts_text": "aaaa",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "CALL_ME_BACK",
          "created_at": "2019-01-22 11:53:49",
          "updated_at": "2019-01-22 11:53:49"
        },
        {
          "_id": 1390,
          "user_id": 448,
          "length": 1,
          "orig_filename": "FeCV361a28Gw5Jgb.wav",
          "map_filename": "FeCV361a28Gw5Jgb.wav",
          "extension": "wav",
          "stripped_name": "FeCV361a28Gw5Jgb",
          "tts_language": "Kate",
          "tts_text": "jihun",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-01-22 11:49:14",
          "updated_at": "2019-01-22 11:49:14"
        },
        {
          "_id": 1389,
          "user_id": 448,
          "length": 1,
          "orig_filename": "bsnhic4Zv0lIdT7h.wav",
          "map_filename": "bsnhic4Zv0lIdT7h.wav",
          "extension": "wav",
          "stripped_name": "bsnhic4Zv0lIdT7h",
          "tts_language": "Kate",
          "tts_text": "aaasa",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "TEMPLATE",
          "created_at": "2019-01-22 11:48:59",
          "updated_at": "2019-01-22 11:48:59"
        },
        {
          "_id": 1388,
          "user_id": 448,
          "length": 1,
          "orig_filename": "aQWzq6WqReVLVHmz.wav",
          "map_filename": "aQWzq6WqReVLVHmz.wav",
          "extension": "wav",
          "stripped_name": "aQWzq6WqReVLVHmz",
          "tts_language": "Kate",
          "tts_text": "asdasd",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2018-12-24 17:14:29",
          "updated_at": "2018-12-24 17:14:29"
        },
        {
          "_id": 1387,
          "user_id": 448,
          "length": 1,
          "orig_filename": "CkGfiHjy0mfyjdlC.wav",
          "map_filename": "CkGfiHjy0mfyjdlC.wav",
          "extension": "wav",
          "stripped_name": "CkGfiHjy0mfyjdlC",
          "tts_language": "Kate",
          "tts_text": "asdasd",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2018-12-24 17:14:17",
          "updated_at": "2018-12-24 17:14:17"
        },
        {
          "_id": 1386,
          "user_id": 448,
          "length": 1,
          "orig_filename": "nxdEiruL9CqhFo8e.wav",
          "map_filename": "nxdEiruL9CqhFo8e.wav",
          "extension": "wav",
          "stripped_name": "nxdEiruL9CqhFo8e",
          "tts_language": "Kate",
          "tts_text": "asdasd",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2018-12-24 14:04:37",
          "updated_at": "2018-12-24 14:04:37"
        },
        {
          "_id": 1379,
          "user_id": 448,
          "length": 2,
          "orig_filename": "BDaK7js5u5dOkQ5G.wav",
          "map_filename": "BDaK7js5u5dOkQ5G.wav",
          "extension": "wav",
          "stripped_name": "BDaK7js5u5dOkQ5G",
          "tts_language": "Alice-ML",
          "tts_text": "blablabla",
          "is_template": 1,
          "cost": 0,
          "type": "TTS",
          "saved_from": "COMPOSE",
          "created_at": "2018-12-13 13:23:56",
          "updated_at": "2018-12-13 13:23:56"
        }
      ],
      "page": 2,
      "count": 63,
      "total_templates_count": 63
    }
  }