import { createActions } from 'redux-actions';

const {
  clearGroup,
  getPhoneGroup,              //phoneGroup--info
  getPhoneGroupSucceed,
  getPhoneGroupFailed,
  removeGroup,
  removeGroupSucceed,
  removeGroupFailed,
  mergeGroup,
  mergeGroupSucceed,
  mergeGroupFailed,
  getContacts,                //phonNumbers of phoneGroup
  getContactsSucceed,
  getContactsFailed,
  getCampaignPhoneNumbers,           //campaignPhoneNumbers for statistics view
  getCampaignPhoneNumbersSucceed,
  getCampaignPhoneNumbersFailed,
  getBlackList,
  getBlackListSucceed,
  getBlackListFailed,
  clearContacts,
  addNumberToBlackList,
  addNumberToBlackListSucceed,
  addNumberToBlackListFailed,
  removeNumberFromBlackList,
  removeNumberFromBlackListSucceed,
  removeNumberFromBlackListFailed,
  exportContacts,

} = createActions({
  CLEAR_GROUP: ()=>({}),
  GET_PHONE_GROUP: params => ({ params }),
  GET_PHONE_GROUP_SUCCEED: groupData => ({ groupData }),
  GET_PHONE_GROUP_FAILED: error => ({ error }),
  REMOVE_GROUP: (params) => ({params}),
  REMOVE_GROUP_SUCCEED: (succeed) => ({succeed}),
  REMOVE_GROUP_FAILED:(error) => ({error}),
  MERGE_GROUP: (params) => ({params}),
  MERGE_GROUP_SUCCEED: (succeed) => ({succeed}),
  MERGE_GROUP_FAILED:(error) =>({error}),
  GET_CONTACTS: params => ({params}),
  GET_CONTACTS_SUCCEED: contactsData => ({contactsData}),
  GET_CONTACTS_FAILED: error => ({error}),
  GET_CAMPAIGN_PHONE_NUMBERS: params => ({params}),
  GET_CAMPAIGN_PHONE_NUMBERS_SUCCEED : campaignPhoneNumberData => ({campaignPhoneNumberData}),
  GET_CAMPAIGN_PHONE_NUMBERS_FAILED: error => ({error}),
  GET_BLACK_LIST: (params) => ({params}),
  GET_BLACK_LIST_SUCCEED: (blackListData) => ({blackListData}),
  GET_BLACK_LIST_FAILED: (error) =>({error}),
  CLEAR_CONTACTS:()=>({}),
  ADD_NUMBER_TO_BLACK_LIST: (params) => ({params}),
  ADD_NUMBER_TO_BLACK_LIST_SUCCEED:(succeed) => ({succeed}),
  ADD_NUMBER_TO_BLACK_LIST_FAILED: (error) => ({error}),
  REMOVE_NUMBER_FROM_BLACK_LIST: (params) =>({params}),
  REMOVE_NUMBER_FROM_BLACK_LIST_SUCCEED: (succeed)=>({succeed}),
  REMOVE_NUMBER_FROM_BLACK_LIST_FAILED:(error) => ({error}),
  EXPORT_CONTACTS: (groupData) => ({groupData}),
});

export {
  clearGroup,
  getPhoneGroup,
  getPhoneGroupSucceed,
  getPhoneGroupFailed,
  removeGroup,
  removeGroupSucceed,
  removeGroupFailed,
  mergeGroup,
  mergeGroupSucceed,
  mergeGroupFailed,
  getContacts,
  getContactsSucceed,
  getContactsFailed,
  getCampaignPhoneNumbers,
  getCampaignPhoneNumbersSucceed,
  getCampaignPhoneNumbersFailed,
  getBlackList,
  getBlackListSucceed,
  getBlackListFailed,
  clearContacts,
  addNumberToBlackList,
  addNumberToBlackListSucceed,
  addNumberToBlackListFailed,
  removeNumberFromBlackList,
  removeNumberFromBlackListSucceed,
  removeNumberFromBlackListFailed,
  exportContacts,
};
