export const invoicesDate = {
    "resource": {
      "error": {
        "no": 0,
        "text": "invoices__1"
      },
      "invoices": [
        {
          "_id": 311,
          "user_id": 448,
          "customer_name": "info@callburn.com",
          "customer_address": "4",
          "customer_postal_code": "d3231",
          "customer_city": null,
          "customer_country_code": "ES",
          "invoice_date": "2019-05-13 19:41:29",
          "invoice_number": "ES-I-201905-00001",
          "order_number": "2019-#1843048",
          "purchased_amount": 10,
          "vat_amount": 2.1,
          "vat_percentage": 21,
          "vat_id": "EStestvatid",
          "total_amount": 12.1,
          "discount_percentage": null,
          "discount_amount": 0,
          "discount_coupon_code": null,
          "currency": "EUR",
          "recharge_cost": 0,
          "remaining_purchased_amount": 10,
          "method": "bank",
          "vendor_response_json": null,
          "is_refunded": 0,
          "is_paid": 1,
          "current_balance_after_billing": 546.4755,
          "type": "TRANSACTION",
          "description": null,
          "original_invoice_number": null,
          "manual_service_id": null,
          "is_manual": 0,
          "created_at": "2019-05-13 18:44:45",
          "updated_at": "2019-05-13 19:41:29",
          "deleted_at": null
        },
        {
          "_id": 309,
          "user_id": 448,
          "customer_name": "N/A",
          "customer_address": "addsa",
          "customer_postal_code": "d3231",
          "customer_city": null,
          "customer_country_code": "IT",
          "invoice_date": "2019-02-27 20:28:05",
          "invoice_number": "IT-S-201902-00003",
          "order_number": "2019-#2018187",
          "purchased_amount": 4,
          "vat_amount": 0,
          "vat_percentage": 0,
          "vat_id": "IT43287743278342",
          "total_amount": 4,
          "discount_percentage": null,
          "discount_amount": null,
          "discount_coupon_code": null,
          "currency": "EUR",
          "recharge_cost": 0,
          "remaining_purchased_amount": 0,
          "method": "not_selected",
          "vendor_response_json": null,
          "is_refunded": 0,
          "is_paid": 1,
          "current_balance_after_billing": 279.3004,
          "type": "MANUAL_SERVICE",
          "description": "testt",
          "original_invoice_number": null,
          "manual_service_id": 3,
          "is_manual": 0,
          "created_at": "2019-02-27 20:28:05",
          "updated_at": "2019-02-27 20:28:05",
          "deleted_at": null
        },
        {
          "_id": 308,
          "user_id": 448,
          "customer_name": "N/A",
          "customer_address": "addsa",
          "customer_postal_code": "d3231",
          "customer_city": null,
          "customer_country_code": "IT",
          "invoice_date": "2019-02-27 20:27:14",
          "invoice_number": "IT-S-201902-00002",
          "order_number": "2019-#5034382",
          "purchased_amount": 10,
          "vat_amount": 0,
          "vat_percentage": 0,
          "vat_id": "IT43287743278342",
          "total_amount": 10,
          "discount_percentage": null,
          "discount_amount": null,
          "discount_coupon_code": null,
          "currency": "EUR",
          "recharge_cost": 0,
          "remaining_purchased_amount": 0,
          "method": "not_selected",
          "vendor_response_json": null,
          "is_refunded": 0,
          "is_paid": 1,
          "current_balance_after_billing": 283.3004,
          "type": "MANUAL_SERVICE",
          "description": "test",
          "original_invoice_number": null,
          "manual_service_id": 2,
          "is_manual": 0,
          "created_at": "2019-02-27 20:27:14",
          "updated_at": "2019-02-27 20:27:14",
          "deleted_at": null
        },
        {
          "_id": 307,
          "user_id": 448,
          "customer_name": "info@callburn.com",
          "customer_address": "addsa",
          "customer_postal_code": "d3231",
          "customer_city": "ddsad",
          "customer_country_code": "IT",
          "invoice_date": "2019-02-09 14:05:15",
          "invoice_number": "IT-I-201902-00003",
          "order_number": "2019-#3992937",
          "purchased_amount": 0,
          "vat_amount": 0,
          "vat_percentage": 0,
          "vat_id": null,
          "total_amount": 0,
          "discount_percentage": 0,
          "discount_amount": 2,
          "discount_coupon_code": null,
          "currency": "EUR",
          "recharge_cost": 0,
          "remaining_purchased_amount": 0,
          "method": "not_selected",
          "vendor_response_json": null,
          "is_refunded": 0,
          "is_paid": 1,
          "current_balance_after_billing": 374.6964,
          "type": "GIFT",
          "description": null,
          "original_invoice_number": null,
          "manual_service_id": null,
          "is_manual": 0,
          "created_at": "2019-02-09 14:05:15",
          "updated_at": "2019-02-09 14:05:15",
          "deleted_at": null
        },
        {
          "_id": 306,
          "user_id": 448,
          "customer_name": "info@callburn.com",
          "customer_address": "addsa",
          "customer_postal_code": "d3231",
          "customer_city": "ddsad",
          "customer_country_code": "IT",
          "invoice_date": "2019-02-09 14:05:15",
          "invoice_number": "IT-I-201902-00002",
          "order_number": "2019-#1740961",
          "purchased_amount": 0,
          "vat_amount": 0,
          "vat_percentage": 0,
          "vat_id": null,
          "total_amount": 0,
          "discount_percentage": 0,
          "discount_amount": 2,
          "discount_coupon_code": null,
          "currency": "EUR",
          "recharge_cost": 0,
          "remaining_purchased_amount": 0,
          "method": "not_selected",
          "vendor_response_json": null,
          "is_refunded": 0,
          "is_paid": 1,
          "current_balance_after_billing": 372.6964,
          "type": "GIFT",
          "description": null,
          "original_invoice_number": null,
          "manual_service_id": null,
          "is_manual": 0,
          "created_at": "2019-02-09 14:05:15",
          "updated_at": "2019-02-09 14:05:15",
          "deleted_at": null
        }
      ],
      "count": 8,
      "page": 1
    }
  };